---
title: "Homework 3"
author: "Saksham Shori"
output:
  html_document:
    toc: true
    toc_float: true
  word_document:
    toc: true
  pdf_document:
    toc: true
---

```{r global_options, echo=FALSE}
knitr::opts_chunk$set(fig.height=3, fig.width=4, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60))
```

```{r}
library(dplyr)
library(magrittr)
library(ggplot2)
setwd("/Users/sakshamshori/Documents/RStudio/sds315")
profs = read.csv("profs.csv")
head(profs)
names(profs)
```

```{r}
#Question 1
#Part A: average course eval score, histogram
hist(profs$eval)

#Part B: side by side box plots for Y/N native speakers
library(ggplot2)
ggplot(profs, aes(x = native, y = eval, fill = native)) + geom_boxplot() + labs(
  title = "Distribution of Course Evaluation Scores by Native English Speaker Status",
  x = "Native English Speaker", y = "Course Evaluation Scores") +
  scale_fill_manual(values = c("lightblue", "lightgreen")) + theme_minimal()

#Part C: facet wrap for male/female instructors
#ggplot(profs, aes(x = eval, fill = gender)) + geom_histogram(bindwidth = 1) + facet_wrap(~prof)

ggplot(profs, aes(x = eval, fill = gender)) + geom_histogram(binwidth = 0.5) +
  facet_wrap(~ gender, nrow = 2) + labs(
    title = "Distribution of Course Evaluation Scores by Gender",
    x = "Course Evaluation Scores", y = "Count") +
  theme_minimal()

#Part D: physical attractiveness & course eval correlation

ggplot(profs, aes(x = eval, y=beauty)) + geom_point(color = "pink") + labs(
    title = "Distribution of Course Evaluation Scores by Attractiveness",
    x = "Course Evaluation Scores", y = "Attractive Scale") +
  theme_minimal()

```


### **Problem 2**

```{r}
bikes = read.csv("bikeshare.csv")
names(bikes)

#Plot A: line graph for hourly bike rentals (total) across all hours of the day
bikeperhr = aggregate(total ~ hr, data = bikes, FUN = mean)
ggplot(bikeperhr) + geom_line(aes(x = hr, y = total)) + labs(title = "Hours Bike Rentals across full day (hrs)", x = "Hours", y = "Total Bike Rentals")

#Plot B:  faceted line graph showing average bike rentals by hour of the day, faceted to whether it is a working day (workingday)
avg_bikerental <- bikes %>%
  group_by(hr, workingday) %>%
  summarize(avg_rentals = mean(total))
ggplot(avg_bikerental, aes(x=hr, y=avg_rentals)) + facet_wrap(~ workingday) + geom_point(color = "red") + geom_line(col="black") + labs(title = "Average Hourly Bike Rentals per Working Day", x="Hour", y="Average Rentals")

#Plot C: 
morning_rides <- bikes %>%
  filter(hr == 9) %>% group_by(weathersit, workingday) %>%
  summarize(avg_rentals = mean(total))

ggplot(morning_rides, aes(x = weathersit, y = avg_rentals)) + geom_bar(stat = "identity", col="orange", fill="pink") + facet_wrap(~ workingday)
  labs(title = "2.C: Average Rentals at 9 AM by Weather and Working Day",
       x = "Weather Situation", y = "Average Rentals") + theme_minimal()

```



### **Problem 3**

```{r}
#Plot 1:
metro = read.csv("capmetro_UT.csv")
names(metro)
#One faceted line graph that plots average boardings by hour of the day, day of week, and month. You should facet by day of week. Each facet should include three lines of average boardings (y) by hour of the day (x), one line for each month and distinguished by color

aggregated_data <- metro %>%
  group_by(hour_of_day, day_of_week, month) %>%
  summarize(avg_boardings = mean(boarding, na.rm = TRUE))

# Create the faceted line graph
ggplot(aggregated_data, aes(x = hour_of_day, y = avg_boardings, color = month)) + geom_line(size = 1) + facet_wrap(~ day_of_week) + labs(
    title = "Average Boardings by Hour of Day, Day of Week, and Month",
    x = "Hour of the Day", y = "Average Boardings", color = "Month") + theme_minimal()

#Plot 2: One faceted scatter plot showing boardings (y) vs. temperature (x), faceted by hour of the day, and with points colored in according to whether it is a weekday or weekend.
#boardingtemp = metro %>% group_by(boarding, temperature)

ggplot(metro, aes(x = temperature, y = boarding, color = weekend)) + geom_point(size = 1) + facet_wrap(~ hour_of_day) + theme_minimal() + labs(title = "Boardings vs. Temp. per hour of the day", x = "Temperature (F)", y = "Boardings")
```

### **Problem 4**

```{r}
billboard = read.csv("billboard.csv")
#PartA: Make a table of the top 10 most popular songs since 1958, as measured by the total number of weeks that a song spent on the Billboard Top 100.
#billinfo = %>%
top10song = billboard %>% filter(year != 1985 & year != 2021) %>%
  group_by(performer, song) %>% summarise(count = n()) %>% arrange(desc(count))

head(top10song, 10)

  
#PartB: musical diversity, how many unique on billbaord chart
uniquemusic = billboard %>% filter(year != 1958 & year != 2021) %>%  
  group_by(year) %>% summarise(unique_songs = length(unique(song)))

ggplot(uniquemusic, aes(x=year, y=unique_songs)) + geom_line(col = "brown") + labs(title = "4.B: Musical Diversity over Time", x = "Year", y = "Frequency")

#Part C:19 artists in U.S. musical history since 1958 who have had at least 30 songs that were “ten-week hits.”
tenweek_hits <- billboard %>% group_by(performer, song) %>%
  summarize(total_weeks = n(), .groups = "drop") %>% filter(total_weeks >= 10)
#filter to > 10 weeks on chart

top10artists = tenweek_hits %>%
  group_by(performer) %>% summarize(num_tenweeks = n(), .groups = "drop") %>% filter(num_tenweeks >= 30) %>% arrange(desc(num_tenweeks))
#put in descending order to see top artistis with more 10 week hits

#ten-week hits per artist
ggplot(top10artists, aes(x = reorder(performer, num_tenweeks), y = num_tenweeks)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flip axes for better readability
  labs(title = "Top Artists with 30+ Ten-Week Hits",
       x = "Performer",
       y = "Number of Ten-Week Hits") +
  theme_minimal()

```